### ISSUE TITLE
install failled

### ISSUE THREAD

**Issue by Phrixus2023** [Z-L-D/TripoSR-webui#1]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Requirement already satisfied: imageio[ffmpeg] in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (2.33.1)
Requirement already satisfied: numpy in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (from imageio[ffmpeg]) (1.26.2)
Requirement already satisfied: pillow>=8.3.2 in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (from imageio[ffmpeg]) (9.5.0)
Requirement already satisfied: imageio-ffmpeg in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (from imageio[ffmpeg]) (0.4.9)
Requirement already satisfied: psutil in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (from imageio[ffmpeg]) (5.9.5)
Requirement already satisfied: setuptools in d:\baidunetdiskdownload\webui_forge_cu121_torch21\system\python\lib\site-packages (from imageio-ffmpeg->imageio[ffmpeg]) (69.0.3)
Collecting git+https://github.com/tatsy/torchmcubes.git
  Cloning https://github.com/tatsy/torchmcubes.git to c:\users\hatm1\appdata\local\temp\pip-req-build-0mnwpf30
  Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: torchmcubes
  Building wheel for torchmcubes (setup.py): started
  Building wheel for torchmcubes (setup.py): finished with status 'error'
  Running setup.py clean for torchmcubes
Failed to build torchmcubes
Error: Expected end or semicolon (after name and no valid version specifier)
    git+https://github.com/tatsy/torchmcubes.git
       ^
Launching Web UI with arguments:
Total VRAM 24564 MB, total RAM 16174 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: TripoSR.py
    Traceback (most recent call last):
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\scripts\TripoSR.py", line 24, in <module>
        import rembg
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\rembg\__init__.py", line 5, in <module>
        from .bg import remove
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\rembg\bg.py", line 16, in <module>
        from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
    ModuleNotFoundError: No module named 'pymatting'

---
Loading weights [1fe6c7ec54] from D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\Stable-diffusion\juggernautXL_version6Rundiffusion.safetensors
2024-03-11 04:54:06,300 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Startup time: 70.4s (prepare environment: 56.0s, import torch: 4.9s, import gradio: 1.4s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 0.9s, load scripts: 2.8s, create ui: 1.0s, gradio launch: 2.0s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  17956.2353515625
[Memory Management] Model Memory (MB) =  0.03814697265625
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  16932.197204589844
Moving model(s) has taken 0.08 seconds
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  17956.1826171875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  14787.827919006348
Moving model(s) has taken 1.49 seconds
Model loaded in 19.3s (load weights from disk: 1.1s, forge instantiate config: 1.5s, forge load real models: 14.1s, calculate empty prompt: 2.5s).

**Comment by Z-L-D** [comment]
Can you let me know what version of WebUI you are using? I assume based on this log that its Forge base but I want to make sure. Also, can you tell me what steps you took to install this?

**Comment by Z-L-D** [comment]
This was an issue I created when moving rembg into the repository. It should now be resolved.
