### ISSUE TITLE
do not work，forge is latest version

### ISSUE THREAD

**Issue by Phrixus2023** [Z-L-D/TripoSR-webui#2]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching with TripoSR-webui installed...
Launching Web UI with arguments:
Total VRAM 8192 MB, total RAM 16174 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 with Max-Q Design : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.float32
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: TripoSR.py
    Traceback (most recent call last):
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\scripts\TripoSR.py", line 27, in <module>
        from tsr.system import TSR
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\tsr\system.py", line 16, in <module>
        from .models.isosurface import MarchingCubeHelper
      File "D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\tsr\models\isosurface.py", line 6, in <module>
        from torchmcubes import marching_cubes
    ModuleNotFoundError: No module named 'torchmcubes'

---
Loading weights [1fe6c7ec54] from D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\models\Stable-diffusion\juggernautXL_version6Rundiffusion.safetensors
2024-03-11 16:27:31,076 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Startup time: 21.9s (prepare environment: 5.4s, import torch: 4.8s, import gradio: 1.5s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 1.0s, load scripts: 4.6s, create ui: 1.0s, gradio launch: 2.1s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7158.99609375
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3990.6413955688477
Moving model(s) has taken 0.90 seconds
Model loaded in 21.2s (load weights from disk: 1.0s, forge instantiate config: 1.8s, forge load real models: 16.5s, calculate empty prompt: 1.7s).

**Comment by Z-L-D** [comment]
Can you go to your extensions folder here: 
`D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\`
And delete the entire 'TripoSR-webui' folder. 

Open CMD and perform another git pull:
`cmd.exe`
`d:`
`cd D:\BaiduNetdiskDownload\webui_forge_cu121_torch21\webui\extensions\`
`git pull https://github.com/Z-L-D/TripoSR-webui`

Then launch Web UI again and during startup, it should attempt to install again. Copy and paste that info for me as well. So far, I haven't had any issues with torchmcubes installing on any of the machines I've tried this with.

**Comment by ThatDocBoi** [comment]
Using a clean latest forge download, when I delete the folder I get this error during the pull command:
```
C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions>git pull https://github.com/Z-L-D/TripoSR-webui
From https://github.com/Z-L-D/TripoSR-webui
 * branch              HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```
If I just re-pull the extension then this error keeps coming up even after I pip install git+https://github.com/tatsy/torchmcubes.git


```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Launching with TripoSR-webui installed...
Launching Web UI with arguments:
Total VRAM 10240 MB, total RAM 49078 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: TripoSR.py
    Traceback (most recent call last):
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\scripts\TripoSR.py", line 27, in <module>
        from tsr.system import TSR
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\tsr\system.py", line 16, in <module>
        from .models.isosurface import MarchingCubeHelper
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\tsr\models\isosurface.py", line 6, in <module>
        from torchmcubes import marching_cubes
    ModuleNotFoundError: No module named 'torchmcubes'

---
Loading weights [15012c538f] from C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-03-11 18:15:07,390 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
model_type EPS
UNet ADM Dimension 0

To create a public link, set `share=True` in `launch()`.
Startup time: 12.0s (prepare environment: 2.7s, import torch: 3.2s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.1s, other imports: 0.6s, load scripts: 2.9s, create ui: 0.5s, gradio launch: 0.4s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  9086.9990234375
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7608.791400909424
Moving model(s) has taken 0.07 seconds
Model loaded in 2.6s (load weights from disk: 0.6s, forge load real models: 1.6s, calculate empty prompt: 0.4s).
```

If I run the pip uninstall torchmcubes command and pip install git+https://github.com/tatsy/torchmcubes.git
 it installs but still errors when opening (guess it's not installing in the environment). Chatgpt suggested I do this:
` C:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\python.exe -m pip install git+https://github.com/tatsy/torchmcubes.git`

but this gives me this error:
```
C:\Users\Artur\Downloads\webui_forge_cu121_torch21>C:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\python.exe -m pip install git+https://github.com/tatsy/torchmcubes.git
Collecting git+https://github.com/tatsy/torchmcubes.git
  Cloning https://github.com/tatsy/torchmcubes.git to c:\users\artur\appdata\local\temp\pip-req-build-2i_kh73w
  Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git 'C:\Users\Artur\AppData\Local\Temp\pip-req-build-2i_kh73w'
  Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torchmcubes
  Building wheel for torchmcubes (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running bdist_wheel
      C:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\torchmcubes
      copying torchmcubes\__init__.py -> build\lib.win-amd64-cpython-310\torchmcubes
      running build_ext
      C:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      CUDA environment was not successfully loaded!
      Build only CPU module!
      running bdist_wheel
      running build
      running build_py
      copying torchmcubes\__init__.py -> build\lib.win-amd64-cpython-310\torchmcubes
      running build_ext
      building 'torchmcubes_module' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\cxx
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\include -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\include\TH -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\include\THC -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\include -IC:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpcxx/grid_interp_cpu.cpp /Fobuild\temp.win-amd64-cpython-310\Release\cxx/grid_interp_cpu.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=torchmcubes_module -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
      grid_interp_cpu.cpp
      C:\Users\Artur\Downloads\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchmcubes
  Running setup.py clean for torchmcubes
Failed to build torchmcubes
ERROR: Could not build wheels for torchmcubes, which is required to install pyproject.toml-based projects

C:\Users\Artur\Downloads\webui_forge_cu121_torch21>
```
Any tips?

**Comment by Z-L-D** [comment]
For the first portion, I'm kind of at a loss. I'm not sure why there would be any supposed history it would think it was merging if this was truly a fresh install of Forge. Have you modified how Git operates on your computer in any way, specifically caching? There is an option in Git that allows you to ignore the error. Here is that command: `git pull https://github.com/Z-L-D/TripoSR-webui --allow-unrelated-histories`. Whether that might cause some unforeseen further issues would remain to be seen as again, it isn't clear why Git thinks there is any history related to the repository at all.

For the second issue, its first important that if your are installing libraries directly into something like Web UI, that you first enter into the python environment prior to installing it.
`cmd.exe`
`cd C:\Users\Artur\Downloads\webui_forge_cu121_torch21>`
`venv\Scripts\activate`
`pip install git+https://github.com/tatsy/torchmcubes.git`

As for the specific error, make sure you have either Visual Studio installed with the C++ build tools or "Build Tools for Visual Studio 2022" installed. I think the real issue though, is that you need to run the command in the python virtual environment though.

**Comment by ThatDocBoi** [comment]
Hmm, so I just opened webui.bat and that error seemed to go away, I think the latest forge build skips the venv as it didn't generate when I started it via run.bat. However now I'm getting that other rembg error:
```
ControlNet preprocessor location: C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor*** Error loading script: TripoSR.py
    Traceback (most recent call last):
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\scripts\TripoSR.py", line 24, in <module>
        import rembg
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\rembg\__init__.py", line 5, in <module>
        from .bg import remove
      File "C:\Users\Artur\Downloads\webui_forge_cu121_torch21\webui\extensions\TripoSR-webui\rembg\bg.py", line 16, in <module>
        from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
    ModuleNotFoundError: No module named 'pymatting'
```

I just pulled the latest commit as well and no change. Not sure what to do now, any help appreciated.

edit: ok so I activated the venv, pip installed pymatting, then it errored for pooch so I installed that, then I ran the "pip install git+https://github.com/tatsy/torchmcubes.git" and it seems to work. It does say "torchmcubes was not compiled with CUDA support, use CPU version instead." but I can see GPU usage and it seems to work.

**Comment by Z-L-D** [comment]
Good to hear. Sorry for the bad installation experience. I'll look into a more robust installation for the next release. As for the torchmcubes error, that one can be really hard to get rid of. Thankfully, it doesn't seem to impact performance dramatically in most cases that I've seen.

**Comment by ThatDocBoi** [comment]
It's all good, I appreciate the work you put in to create the extension!

**Comment by Phrixus2023** [comment]
I got it working, I installed torchmcubes using the system's python and then just copied it to the forge environment

**Comment by Z-L-D** [comment]
Apologies to you for the rough installation as well. Glad to hear you were able to get it working!
